# Generated by Django 4.0.4 on 2022-11-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['event_date']},
        ),
    ]
